name: 'OZI Provenance'
description: 'Generate provenance attestations for OZI build artifacts'
author: 'OZI Project'
branding:
  color: 'blue'
  icon: 'lock'
runs:
  using: composite
  steps:
    - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
      with:
        name: prerelease
    - uses: actions/attest-build-provenance@v2
      with:
        subject-path: 'dist/*'
        push-to-registry: true
