name: 'OZI Provenance'
description: 'Generate provenance attestations for OZI build artifacts'
author: 'OZI Project'
branding:
  color: 'blue'
  icon: 'lock'
runs:
  using: composite
  steps:
    - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
    - id: attest
      uses: actions/attest-build-provenance@db473fddc028af60658334401dc6fa3ffd8669fd # 2.3.0
      with:
        subject-path: 'artifact/dist/*'
    - run: gh release upload ${{ github.event.release.tag_name }} ${{ steps.attest.outputs.bundle-path }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
      shell: bash
